/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import Controller.Controller;

/**
 *
 * @author Adeesha
 */
public class EventSelect extends javax.swing.JFrame {
    
    private static  boolean isMale;
    InformationFrame newEvent = new InformationFrame();
    /**
     * Creates new form EventSelect
     */
    public EventSelect() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();
        genderLabel = new javax.swing.JLabel();
        storkLabel = new javax.swing.JLabel();
        storkComboBox = new javax.swing.JComboBox();
        nextButton = new javax.swing.JButton();
        headLine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(maleRB);
        maleRB.setSelected(true);
        maleRB.setText("Male");

        buttonGroup1.add(femaleRB);
        femaleRB.setText("Female");

        genderLabel.setText("Gender:");

        storkLabel.setText("Stork:");

        storkComboBox.setMaximumRowCount(5);
        storkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "                ", "Free Style", "Back Stork", "Breast Stork", "Butterfly Stork" }));
        storkComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                storkComboBoxItemStateChanged(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        headLine.setFont(new java.awt.Font("DokChampa", 1, 24)); // NOI18N
        headLine.setText("Choose Your Event");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nextButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(storkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(femaleRB)))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(storkLabel)
                            .addComponent(genderLabel))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(headLine)
                .addGap(18, 18, 18)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRB)
                    .addComponent(femaleRB))
                .addGap(18, 18, 18)
                .addComponent(storkLabel)
                .addGap(13, 13, 13)
                .addComponent(storkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setIsMale(){
        if (maleRB.isSelected()){
            isMale = true;
        }
        else{
            isMale = false;
        }
    }
    
    public static boolean getIsMale(){
        return isMale;
    }
    private void storkComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_storkComboBoxItemStateChanged
          if (evt.getStateChange() == ItemEvent.SELECTED){
            Controller.setStork(storkComboBox.getSelectedIndex(),isMale);
        }
    }//GEN-LAST:event_storkComboBoxItemStateChanged

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        setIsMale();
        if (storkComboBox.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Please Select Stork");
        }
        else{
            
            this.dispose();
            newEvent.setSize(750, 650);
            newEvent.setVisible(true);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel headLine;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox storkComboBox;
    private javax.swing.JLabel storkLabel;
    // End of variables declaration//GEN-END:variables
}
