/*
 * To change this license header, choose License Headers in Project Properties.
 * To change t
    @Override
    public void setSelectedItem(Object anItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getSelectedItem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public E getElementAt(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
his template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ItemEvent;
import Controller.Controller;

/**
 *
 * @author Adeesha
 */
public class LoadResult extends javax.swing.JFrame {

    /**
     * Creates new form LoadResult
     */
    public LoadResult() {
        initComponents();
      

    }
    
    public String[] getflist(){
        String [] flist = new String [Controller.getFileName().size()];

        for (int i=0;i<Controller.getFileName().size();i++){

            flist[i]=Controller.getFileName().get(i);
        }
        return flist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rankLabel1 = new javax.swing.JLabel();
        rankLabel2 = new javax.swing.JLabel();
        rankLabel3 = new javax.swing.JLabel();
        rankLabel4 = new javax.swing.JLabel();
        rankLabel5 = new javax.swing.JLabel();
        detailLabel1 = new javax.swing.JLabel();
        detailLabel2 = new javax.swing.JLabel();
        detailLabel3 = new javax.swing.JLabel();
        detailLabel4 = new javax.swing.JLabel();
        detailLabel5 = new javax.swing.JLabel();
        fileList = new javax.swing.JComboBox();
        exitButton = new javax.swing.JButton();
        headline1 = new javax.swing.JLabel();
        headline2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rankLabel1.setText("1.");
        jPanel1.add(rankLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 91, -1, -1));

        rankLabel2.setText("2.");
        jPanel1.add(rankLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 115, -1, -1));

        rankLabel3.setText("3.");
        jPanel1.add(rankLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        rankLabel4.setText("4.");
        jPanel1.add(rankLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 165, -1, -1));

        rankLabel5.setText("5.");
        jPanel1.add(rankLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(detailLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 190, 21));
        jPanel1.add(detailLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 115, 180, 20));
        jPanel1.add(detailLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 170, 20));
        jPanel1.add(detailLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 165, 160, 20));
        jPanel1.add(detailLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 20));

        fileList.setModel(new javax.swing.DefaultComboBoxModel(getflist()));
        fileList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fileListItemStateChanged(evt);
            }
        });
        jPanel1.add(fileList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 328, 264));

        headline1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        headline1.setText("Records -");
        getContentPane().add(headline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 21, -1, -1));

        headline2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(headline2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 21, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fileListItemStateChanged
       if (evt.getStateChange() == ItemEvent.SELECTED){
           Controller.loadResult((String) fileList.getSelectedItem());
           headline2.setText((String) fileList.getSelectedItem());
           if(Controller.getLoadReusult().isEmpty()){
               
           }else{
                switch(Controller.getLoadReusult().size()){
                    case 5:
                        detailLabel5.setText(Controller.getLoadReusult().get(4));
                    case 4:
                       detailLabel4.setText(Controller.getLoadReusult().get(3));
                    case 3:
                       detailLabel3.setText(Controller.getLoadReusult().get(2));
                    case 2:
                       detailLabel2.setText(Controller.getLoadReusult().get(1));
                    case 1:
                       detailLabel1.setText(Controller.getLoadReusult().get(0));
               }
           }
       }
    }//GEN-LAST:event_fileListItemStateChanged

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailLabel1;
    private javax.swing.JLabel detailLabel2;
    private javax.swing.JLabel detailLabel3;
    private javax.swing.JLabel detailLabel4;
    private javax.swing.JLabel detailLabel5;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox fileList;
    private javax.swing.JLabel headline1;
    private javax.swing.JLabel headline2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rankLabel1;
    private javax.swing.JLabel rankLabel2;
    private javax.swing.JLabel rankLabel3;
    private javax.swing.JLabel rankLabel4;
    private javax.swing.JLabel rankLabel5;
    // End of variables declaration//GEN-END:variables
}
